<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-CUO3FKB" failures="1" tests="6" name="Personel loan" time="0.277" errors="0" timestamp="2024-07-31T16:37:01 IST">
  <testcase classname="test.SampleDemo" name="Demo" time="0.067">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.SampleDemo.Demo(SampleDemo.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase classname="test.SampleDemo" name="SecondTest" time="0.017"/>
  <testcase classname="test.SampleDemo2" name="Demo" time="0.004"/>
  <testcase classname="test.SampleDemo4" name="LoginApiHomeLoan" time="0.004"/>
  <testcase classname="test.SampleDemo4" name="MobileloginHomeLoan" time="0.009"/>
  <testcase classname="test.SampleDemo4" name="WebloginHomeLoan" time="0.004"/>
</testsuite> <!-- Personel loan -->
